from turtle import *
Turtle(visible=False)
hideturtle()
title('Facebook Logo')
# speed(0)
# bgcolor('black')
pencolor('#1778F2')
goto(0,-200)
fillcolor('#1778F2')
begin_fill()
circle(200)
end_fill()
pencolor('white')
goto(-70,-420)
write('f',font=('Klavika',430))
done() 